[package]
name = "dqk-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dqk-macro = { version = "0.1.0", path = "../dqk-macro" }

# other
serde = { version = "1.0", features = ["derive"] }